# Generated by Django 2.2.7 on 2020-02-17 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pint', '0002_auto_20191123_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='pint.AdType'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='pint.City'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='floor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='pint.Floor'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='img',
            field=models.CharField(default=None, max_length=350),
        ),
        migrations.AlterField(
            model_name='ad',
            name='material',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='pint.Material'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='object_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='pint.ObjectType'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='pint.Room'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='square_all',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='square_kitchen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='square_live',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='url',
            field=models.CharField(default=None, max_length=400, unique=True),
        ),
    ]
