# Generated by Django 2.2.7 on 2020-02-17 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pint', '0003_auto_20200217_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pint.AdType'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pint.City'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='floor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pint.Floor'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='img',
            field=models.CharField(default=None, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='material',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pint.Material'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='object_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pint.ObjectType'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='room',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pint.Room'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='site',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pint.Site'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='url',
            field=models.CharField(default=None, max_length=400, null=True, unique=True),
        ),
    ]
