# Generated by Django 2.2.7 on 2020-02-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pint', '0005_auto_20200217_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='floor',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='pint.Floor'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='room',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='pint.Room'),
        ),
    ]
