# Generated by Django 2.2.7 on 2020-02-18 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pint', '0006_auto_20200218_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='material',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='pint.Material'),
        ),
    ]
