# Generated by Django 2.2.7 on 2020-02-18 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pint', '0007_auto_20200218_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='pint.AdType'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='floor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='pint.Floor'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='material',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='pint.Material'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='pint.Room'),
        ),
    ]
